<?php if ($this->getMaxPriceFloat() != $this->getMinPriceFloat()) : ?>
    <div id="price-range"></div>
    <div style="margin-top: 10px;">
        <div style="float:left">$<span id="slider-min-value"></span></div>
        <div style="float:right">$<span id="slider-max-value"></span></div>
        <div style="clear: both"></div>
    </div>
    <div style="margin: 10px 0;text-align: right">
        <button class="button-primary button-small"
                onclick="javascript: CatalinSeoHandler.handlePriceEvent()">
            <?php echo $this->__('Update') ?>
        </button>
    </div>


    <script type="text/javascript">
        var slider = document.getElementById('price-range');
        noUiSlider.create(slider, {
            start: [<?php echo $this->getCurrentMinPriceFilter(); ?>, <?php echo $this->getCurrentMaxPriceFilter(); ?>],
            connect: true,
            range: {
                'min': <?php echo $this->getMinPriceFloat(); ?>,
                'max': <?php echo $this->getMaxPriceFloat(); ?>
            },
            format: {
                to: function (value) {
                    return Math.round(value);
                },
                from: function (value) {
                    return Math.round(value);
                }
            }
        });

        var priceValues = [
            document.getElementById('slider-min-value'),
            document.getElementById('slider-max-value')
        ];

        slider.noUiSlider.on('update', function (values, handle) {
            priceValues[handle].innerHTML = values[handle];
            CatalinSeoHandler.priceSlider.currentMinPrice = values[0];
            CatalinSeoHandler.priceSlider.currentMaxPrice = values[1];
        });

        <?php if ($this->helper('catalin_seo')->isAjaxEnabled()): ?>
        CatalinSeoHandler.isAjaxEnabled = true;
        <?php endif; ?>
        CatalinSeoHandler.priceSlider.urlTemplate = '<?php echo $this->getUrlPattern(); ?>';
        CatalinSeoHandler.priceSlider.maxPrice = <?php echo $this->getMaxPriceFloat(); ?>;
        CatalinSeoHandler.priceSlider.minPrice = <?php echo $this->getMinPriceFloat(); ?>;
        CatalinSeoHandler.priceSlider.currentMinPrice = <?php echo $this->getCurrentMinPriceFilter(); ?>;
        CatalinSeoHandler.priceSlider.currentMaxPrice = <?php echo $this->getCurrentMaxPriceFilter(); ?>;
        CatalinSeoHandler.bindPriceSlider();
    </script>
<?php else: ?>
    <span><?php echo $this->__('Price filter not available.'); ?></span>
<?php endif; ?>